version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ${JOOMLA_MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${JOOMLA_ADMIN_PASS}
      MYSQL_DATABASE: ${JOOMLA_DB_NAME}
      MYSQL_USER: ${JOOMLA_DB_USER}
      MYSQL_PASSWORD: ${JOOMLA_DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

